apiVersion: v1
kind: Service
metadata:
  name: loan
  namespace: default
  labels:
    app: loan
spec:
  selector:
    app: loan
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer